version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
